### ISSUE TITLE
Sửa đường link của web từ 

### ISSUE THREAD

**Issue by truonghaibg** [truonghaibg/pjm.vn#1]
CHuyển từ http://localhost/pjm.vn/public/ thành http://localhost/pjm.vn/

**Comment by vuhien502** [comment]
không nên sửa.Để đó lúc nào có host với tên miền thì chỉ thẳng vào public

**Comment by truonghaibg** [comment]
Đã sửa lại đường dẫn cho web tham khảo link
https://vietpro.net.vn/laravel-02-cai-dat-va-toi-uu-duong-dan-trong-laravel.html
